### ISSUE TITLE
Marker not drawn at startup

### ISSUE THREAD

**Issue by sdellachiesa** [sdellachiesa/KST#7]
I changed the dashboard and added the sidebar, but I got a strange bug.

The App doesn´t draw the Markers when it starts.
by default should draw the red markers.
It seems to require an Initial slider input.

In fact, by moving the slider it works.
This bug appeared after adding the sidebar with Data and Info.

tricky bug.

**Comment by GiulioGenova** [comment]
Tried a few things but the olny way to solve it is to add the markers inside the actual map "my_leaf".

Solved in commit https://github.com/sdellachiesa/KST/commit/c3eaab256bba52043140ffe0bf6829d1dcdb63da

The problem has to do with the timing of the events at startup.
The map is drawn and after that no change is detected on the filtered (by elevation- slider) table.
This behaviour is actually the desired most of the time,
